### ISSUE TITLE
Tutorial to Analyze Quran Corpus

### ISSUE THREAD

**Issue by blueray453** [quranwbw/tracker#256]
Assalamualaikum Brother.

I am interested in the code of:

![quranic-word](https://github.com/quranwbw/tracker/assets/855297/974d66c2-5cf1-4af3-8ec5-5086f4e7e135)

How was the following found.

- ROOT LETTERS
- WORD GRAMMAR
- VERB FORMS
- DIFFERENT EXAMPLES
- OCCURRENCES IN QURAN (with similar root and the exact word)

I am interested in these sort of analysis (to make a Quran learning course and also to learn my self).

Are the DIFFERENT EXAMPLES from Quran or somewhere else. If I want to get examples from Quran then what to do?

When you have time, can you please give us some guideline on how to do these (ex. which libraries to use, which corpus are you using, how to approach each of the five points etc). Some sample code will also be very useful.

**Comment by marwan** [comment]
Walaikum As-salaam brother,

The data is fetched from our API, you can find the new version on https://v4.quranwbw.com/morphology/105:1:6.

Resources:
https://github.com/kaisdukes/quranic-corpus
https://github.com/mustafa0x/quran-morphology

**Comment by blueray453** [comment]
Jazak Allah Brother.
